import { ArrowUpRight, BookOpen, Play, Sparkles } from "lucide-react";
import { useEffect, useRef, useState, type ReactNode } from "react";
import { Link } from "react-router-dom";
import { tutorials } from "./blogData";

export default function Blog() {
  const [activeId, setActiveId] = useState<string>(tutorials[0].id);
  return <main className="overflow-x-clip bg-[#fcfbfa] text-slate-950 dark:bg-[#0f0c14] dark:text-stone-100">
    <section className="mx-auto max-w-7xl px-6 pb-8 pt-14 lg:px-8 lg:pb-12 lg:pt-20"><div className="grid items-end gap-8 border-b border-slate-200 pb-12 dark:border-white/10 lg:grid-cols-[minmax(0,1fr)_auto]"><div><span className="inline-flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.22em] text-violet-400 dark:text-violet-200"><Sparkles className="size-3" /> The beauty journal</span><h1 className="mt-5 max-w-4xl text-4xl font-semibold leading-[1] tracking-[-.05em] sm:text-6xl">Makeup tutorials,<br />made approachable.</h1><p className="mt-5 max-w-2xl text-sm leading-7 text-slate-500 dark:text-stone-400 sm:text-base">Expert guidance for choosing shades, learning techniques and creating looks that still feel like you.</p></div><div className="flex items-center gap-3 text-slate-500 dark:text-stone-400"><span className="grid size-10 place-items-center rounded-full bg-violet-50 text-violet-400 dark:bg-violet-300/10 dark:text-violet-200"><BookOpen className="size-4" /></span><div><strong className="block text-sm text-slate-950 dark:text-stone-100">{tutorials.length} lessons</strong><span className="text-[10px]">Watch at your own pace</span></div></div></div></section>

    <section className="mx-auto grid max-w-7xl items-start gap-10 px-6 py-16 lg:grid-cols-[270px_minmax(0,1fr)] lg:px-8 lg:py-24">
      <aside className="hidden self-start lg:sticky lg:top-28 lg:block"><div className="max-h-[calc(100vh-8rem)] overflow-y-auto overscroll-contain rounded-[1.75rem] border border-slate-200 bg-white p-4 [scrollbar-width:thin] dark:border-white/10 dark:bg-[#17131d]"><div className="flex items-center gap-3 px-2 pb-4"><span className="grid size-10 place-items-center rounded-2xl bg-violet-50 text-violet-400 dark:bg-violet-300/10 dark:text-violet-200"><BookOpen className="size-4" /></span><div><h2 className="text-sm font-semibold">Contents</h2><p className="mt-0.5 text-[10px] text-slate-400">Jump to a lesson</p></div></div><nav className="space-y-1 border-t border-slate-100 pt-3 dark:border-white/8">{tutorials.map((tutorial, index) => <a key={tutorial.id} href={`#${tutorial.id}`} onClick={() => setActiveId(tutorial.id)} className={`flex items-start gap-3 rounded-xl px-3 py-3 text-xs leading-5 transition ${activeId === tutorial.id ? "bg-violet-50 font-semibold text-violet-600 dark:bg-violet-300/10 dark:text-violet-200" : "text-slate-500 hover:bg-slate-50 hover:text-slate-950 dark:text-stone-400 dark:hover:bg-white/5 dark:hover:text-stone-100"}`}><span className="mt-0.5 text-[9px] font-bold opacity-50">{String(index + 1).padStart(2, "0")}</span><span>{tutorial.title}</span></a>)}</nav></div></aside>

      <div><div className="mb-9 flex flex-wrap items-end justify-between gap-5"><div><p className="text-[10px] font-semibold uppercase tracking-[.22em] text-violet-400 dark:text-violet-200">Watch and learn</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.04em] sm:text-4xl">The tutorial edit</h2></div><p className="max-w-sm text-sm leading-6 text-slate-500 dark:text-stone-400">A considered collection of video guides from beauty creators and professional artists.</p></div><div className="space-y-7">{tutorials.map((tutorial, index) => <Reveal key={tutorial.id} delay={index % 2 * 60}><TutorialCard tutorial={tutorial} index={index} onVisible={() => setActiveId(tutorial.id)} /></Reveal>)}</div></div>
    </section>

    <Reveal><section className="mx-auto mb-20 max-w-7xl px-6 lg:px-8"><div className="flex flex-col items-start justify-between gap-6 rounded-[2rem] bg-violet-50 p-8 dark:bg-[#241738] sm:flex-row sm:items-center sm:p-10"><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-violet-400 dark:text-violet-200">Ready to practise?</p><h2 className="mt-3 text-2xl font-semibold tracking-tight sm:text-3xl">Find the products for your next look.</h2></div><Link to="/products" className="group inline-flex h-12 shrink-0 items-center gap-2 rounded-full bg-slate-950 px-6 text-sm font-semibold text-white transition hover:-translate-y-0.5 hover:bg-violet-400 dark:bg-violet-300 dark:text-violet-950">Shop the collection <ArrowUpRight className="size-4 transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></Link></div></section></Reveal>
  </main>;
}

function TutorialCard({ tutorial, index, onVisible }: { tutorial: (typeof tutorials)[number]; index: number; onVisible: () => void }) {
  const ref = useRef<HTMLElement>(null);
  useEffect(() => { const node = ref.current; if (!node) return; const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting) onVisible(); }, { rootMargin: "-25% 0px -60% 0px" }); observer.observe(node); return () => observer.disconnect(); }, [onVisible]);
  return <article ref={ref} id={tutorial.id} className="scroll-mt-30 overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-[0_25px_70px_-55px_rgba(15,23,42,.4)] transition hover:border-violet-100 dark:border-white/10 dark:bg-[#17131d] dark:hover:border-violet-300/25"><div className="grid lg:grid-cols-[1.18fr_.82fr]"><div className="relative aspect-video overflow-hidden bg-slate-950 lg:aspect-auto lg:min-h-80"><iframe src={`https://www.youtube-nocookie.com/embed/${tutorial.id}`} title={tutorial.title} loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen className="absolute inset-0 size-full" /></div><div className="flex flex-col justify-between p-7 sm:p-9"><div><div className="flex items-center justify-between"><span className="rounded-full bg-violet-50 px-3 py-1.5 text-[9px] font-semibold uppercase tracking-[.16em] text-violet-500 dark:bg-violet-300/10 dark:text-violet-200">{tutorial.category}</span><span className="text-[10px] font-semibold text-slate-300 dark:text-stone-600">{String(index + 1).padStart(2, "0")}</span></div><h3 className="mt-6 text-2xl font-semibold leading-tight tracking-[-.035em]">{tutorial.title}</h3><p className="mt-4 text-sm leading-7 text-slate-500 dark:text-stone-400">{tutorial.description}</p></div><div className="mt-8 flex flex-wrap items-center gap-5"><Link to={`/blogs/${tutorial.id}`} className="group inline-flex h-10 items-center gap-2 rounded-full bg-slate-950 px-5 text-xs font-semibold text-white transition hover:bg-violet-400 dark:bg-violet-300 dark:text-violet-950">Read lesson <ArrowUpRight className="size-3.5 transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></Link><a href={`https://youtu.be/${tutorial.id}`} target="_blank" rel="noreferrer" className="group inline-flex items-center gap-2 text-xs font-semibold text-slate-500 transition hover:text-violet-500 dark:text-stone-400 dark:hover:text-violet-200"><Play className="size-3 fill-current" />YouTube</a></div></div></div></article>;
}

function Reveal({ children, delay = 0 }: { children: ReactNode; delay?: number }) {
  const ref = useRef<HTMLDivElement>(null);
  const [visible, setVisible] = useState(false);
  useEffect(() => { const node = ref.current; if (!node) return; const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting) { setVisible(true); observer.disconnect(); } }, { threshold: .06, rootMargin: "0px 0px -18% 0px" }); observer.observe(node); return () => observer.disconnect(); }, []);
  return <div ref={ref} style={{ transitionDelay: `${delay}ms` }} className={`transition-all duration-500 motion-reduce:transform-none motion-reduce:opacity-100 ${visible ? "translate-y-0 opacity-100" : "translate-y-5 opacity-0"}`}>{children}</div>;
}
