import { ArrowDownRight, ArrowUpRight, CircleDollarSign, Package, ShoppingCart, Users } from "lucide-react";
import { useEffect, useState } from "react";
import { adminResources, products } from "@/data/store";
import { api } from "@/lib/api";

type DashboardData = { summary: { totalSales: number; totalOrders: number; totalCustomers: number; averageOrder: number } };

export default function AdminDashboard() {
  const [data, setData] = useState<DashboardData | null>(null);
  useEffect(() => { api<DashboardData>("/admin/dashboard").then(setData).catch(() => setData(null)); }, []);
  const summary = data?.summary;
  const stats = [{ label: "Revenue", value: summary ? `£${summary.totalSales.toLocaleString("en-GB", { minimumFractionDigits: 2 })}` : "—", change: "All recorded orders", icon: <CircleDollarSign /> }, { label: "Orders", value: summary?.totalOrders.toLocaleString() ?? "—", change: "Database total", icon: <ShoppingCart /> }, { label: "Customers", value: summary?.totalCustomers.toLocaleString() ?? "—", change: "Registered accounts", icon: <Users /> }, { label: "Average order", value: summary ? `£${summary.averageOrder.toFixed(2)}` : "—", change: "Across all orders", icon: <Package /> }];
  return <div><div><p className="text-sm text-slate-500">Tuesday, 18 August</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Dashboard overview</h1></div><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map((stat, index) => <div key={stat.label} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><span className="text-sm text-slate-500">{stat.label}</span><span className="text-slate-400 [&_svg]:size-5">{stat.icon}</span></div><p className="mt-4 text-2xl font-semibold">{stat.value}</p><p className={`mt-2 flex items-center gap-1 text-xs ${index === 3 ? "text-amber-600" : "text-emerald-600"}`}>{index === 3 ? <ArrowDownRight className="size-3" /> : <ArrowUpRight className="size-3" />}{stat.change}</p></div>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-[1fr_360px]"><section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Recent products</h2><a href="/admin/products" className="text-xs font-semibold text-violet-400">View all</a></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-125 text-left text-sm"><thead className="border-b border-slate-100 text-xs text-slate-400"><tr><th className="py-3 font-medium">Product</th><th className="font-medium">Category</th><th className="font-medium">Price</th><th className="font-medium">Status</th></tr></thead><tbody>{products.slice(0, 5).map((product) => <tr key={product.id} className="border-b border-slate-50"><td className="py-3"><div className="flex items-center gap-3"><img src={product.image} className="size-10 rounded-lg bg-stone-50 object-contain" alt="" /><span className="font-medium">{product.name}</span></div></td><td className="text-slate-500">{product.category}</td><td>£{product.price.toFixed(2)}</td><td><span className="rounded-full bg-emerald-50 px-2 py-1 text-xs text-emerald-700">Active</span></td></tr>)}</tbody></table></div></section><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Store management</h2><div className="mt-4 space-y-1">{adminResources.slice(0, 6).map((item) => <a key={item.path} href={`/admin/${item.path}`} className="flex items-center justify-between rounded-xl px-3 py-2.5 text-sm hover:bg-slate-50"><span>{item.label}</span><span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs text-slate-500">{item.count}</span></a>)}</div></section></div></div>;
}
