import { ArrowRight, Check, Heart, Leaf, Sparkles } from "lucide-react";
import { useEffect, useRef, useState, type ReactNode } from "react";
import { Link } from "react-router-dom";

const sections = [
  { eyebrow: "Our philosophy", title: "Beauty, made personal", text: "Welcome to Charm & Grace, your destination for expressive beauty. We are a passionate team dedicated to making every shopping experience thoughtful, inclusive and inspiring.", image: "/about-philosophy-v3.png", position: "center 24%" },
  { eyebrow: "How it began", title: "Our story", text: "Founded in 2022 as a small boutique, Charm & Grace has grown into a community-led beauty store. We curate quality cosmetics that balance modern trends with everyday wearability.", image: "/about-story-v2.png", position: "center 34%" },
  { eyebrow: "Come as you are", title: "Join our community", text: "Explore our collection and discover new ways to make beauty your own. Follow along for product stories, practical tips and inspiration from fellow beauty lovers.", image: "/about-community-v2.png", position: "center" },
];

export default function About() {
  return <main className="overflow-hidden bg-[#fcfbfa] dark:bg-[#0f0c14]">
    <section className="px-4 py-4 sm:px-6 sm:py-6 lg:px-8"><div className="relative mx-auto min-h-[560px] max-w-7xl overflow-hidden rounded-[2.5rem] bg-[#20132f] text-white"><div className="absolute -right-24 -top-32 size-96 rounded-full bg-violet-300/20 blur-3xl" /><div className="absolute -bottom-48 left-1/4 size-96 rounded-full bg-violet-300/10 blur-3xl" /><div className="absolute inset-0 opacity-[.08] [background-image:radial-gradient(circle_at_center,white_1px,transparent_1px)] [background-size:22px_22px]" /><div className="absolute right-12 top-1/2 hidden size-80 -translate-y-1/2 lg:block"><div className="absolute inset-0 rounded-full border border-white/10" /><div className="absolute inset-12 rounded-full border border-white/10" /><div className="absolute inset-24 grid place-items-center rounded-full border border-white/15 bg-white/8 backdrop-blur"><Sparkles className="size-10 text-violet-200" strokeWidth={1.25} /></div><span className="absolute left-8 top-14 size-3 rounded-full bg-violet-200 shadow-[0_0_28px_rgba(221,214,254,.8)]" /><span className="absolute bottom-16 right-5 size-2 rounded-full bg-white/60" /></div><div className="relative flex min-h-[560px] max-w-3xl flex-col justify-center px-7 py-14 sm:px-12 lg:px-18 lg:py-18"><span className="w-fit rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-[10px] font-semibold uppercase tracking-[.22em] text-violet-100 backdrop-blur">Independent beauty · Since 2022</span><h1 className="mt-7 text-5xl font-semibold leading-[.94] tracking-[-.06em] sm:text-7xl lg:text-8xl">More than makeup.</h1><p className="mt-6 max-w-xl text-base leading-7 text-white/65 sm:text-lg">Beauty should feel joyful, individual and easy to explore. We make room for every mood, moment and version of you.</p><Link to="/products" className="group mt-8 inline-flex h-12 w-fit items-center gap-3 rounded-full bg-white px-6 text-sm font-semibold text-slate-950 transition-all hover:-translate-y-0.5 hover:bg-violet-50">Explore our edit <ArrowRight className="size-4 transition-transform group-hover:translate-x-1" /></Link></div></div></section>

    <section className="mx-auto max-w-7xl px-6 py-18 lg:px-8 lg:py-24"><Reveal><div className="grid gap-6 border-y border-slate-200 py-9 dark:border-white/10 sm:grid-cols-3">{[{ icon: <Sparkles />, value: "Thoughtful", label: "Curated, never crowded" }, { icon: <Heart />, value: "Inclusive", label: "Beauty on your terms" }, { icon: <Leaf />, value: "Considered", label: "Choices made with care" }].map((item) => <div key={item.value} className="flex items-center gap-4 sm:justify-center"><span className="grid size-11 place-items-center rounded-2xl bg-violet-50 text-violet-400 dark:bg-violet-300/10 dark:text-violet-200 [&>svg]:size-4.5">{item.icon}</span><div><strong className="block text-sm">{item.value}</strong><span className="mt-1 block text-xs text-slate-400">{item.label}</span></div></div>)}</div></Reveal>
      <div className="mt-16 space-y-8 lg:mt-24">{sections.map((section, index) => <Reveal key={section.title} delay={index * 90}><article className="group grid items-stretch overflow-hidden rounded-[2.25rem] border border-slate-200 bg-white shadow-[0_28px_75px_-58px_rgba(15,23,42,.4)] transition hover:border-violet-100 dark:border-white/10 dark:bg-[#17131d] lg:grid-cols-2"><div className={`relative min-h-80 overflow-hidden lg:min-h-125 ${index % 2 ? "lg:order-2" : ""}`}><img src={section.image} alt={section.title} style={{ objectPosition: section.position }} className="absolute inset-0 size-full object-cover transition-transform duration-500 group-hover:scale-[1.035]" /><div className="absolute inset-0 bg-gradient-to-t from-slate-950/35 to-transparent" /><span className="absolute bottom-5 left-5 grid size-12 place-items-center rounded-full border border-white/20 bg-white/15 text-xs font-semibold text-white backdrop-blur">0{index + 1}</span></div><div className="flex flex-col justify-center p-8 sm:p-12 lg:p-16"><p className="text-[10px] font-semibold uppercase tracking-[.22em] text-violet-400 dark:text-violet-200">{section.eyebrow}</p><h2 className="mt-4 text-3xl font-semibold tracking-[-.04em] sm:text-5xl">{section.title}</h2><p className="mt-6 max-w-lg text-base leading-8 text-slate-600 dark:text-stone-400">{section.text}</p><div className="mt-8 flex items-center gap-2 text-xs font-semibold text-slate-500 dark:text-stone-400"><Check className="size-4 text-violet-300" /> Thoughtfully selected for real life</div></div></article></Reveal>)}</div>
    </section>
    <Reveal><section className="mx-auto mb-20 max-w-7xl px-6 lg:px-8"><div className="relative overflow-hidden rounded-[2.5rem] bg-violet-50 px-7 py-12 text-center dark:bg-[#241738] sm:px-12 sm:py-16"><div className="absolute -right-20 -top-24 size-72 rounded-full bg-violet-200/20 blur-3xl" /><div className="relative"><p className="text-[10px] font-semibold uppercase tracking-[.22em] text-violet-400 dark:text-violet-200">Your next favourite awaits</p><h2 className="mx-auto mt-4 max-w-2xl text-3xl font-semibold tracking-[-.045em] sm:text-5xl">Make beauty entirely your own.</h2><p className="mx-auto mt-4 max-w-xl text-sm leading-7 text-slate-600 dark:text-stone-400">Explore a collection designed for experimenting, expressing and feeling like yourself.</p><Link to="/products" className="group mt-7 inline-flex h-12 items-center gap-2 rounded-full bg-slate-950 px-7 text-sm font-semibold text-white transition hover:-translate-y-0.5 hover:bg-violet-400 dark:bg-violet-400 dark:hover:bg-violet-300">Shop the collection <ArrowRight className="size-4 transition-transform group-hover:translate-x-1" /></Link></div></div></section></Reveal>
  </main>;
}

function Reveal({ children, delay = 0 }: { children: ReactNode; delay?: number }) {
  const ref = useRef<HTMLDivElement>(null);
  const [visible, setVisible] = useState(false);
  useEffect(() => { const node = ref.current; if (!node) return; const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting) { setVisible(true); observer.disconnect(); } }, { threshold: .08, rootMargin: "0px 0px -20% 0px" }); observer.observe(node); return () => observer.disconnect(); }, []);
  return <div ref={ref} style={{ transitionDelay: `${delay}ms` }} className={`transition-all duration-500 motion-reduce:transform-none motion-reduce:opacity-100 ${visible ? "translate-y-0 opacity-100" : "translate-y-5 opacity-0"}`}>{children}</div>;
}
